server:
  port: 8000

spring:
  application:
    name: msvc-gateway
  jwt:
    expiration: ${JWT_EXPIRATION}
    secret: ${JWT_SECRET}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: billing
          uri: lb://msvc-billing
          predicates:
            - Path=/api/v1/billing/**
          filters:
            - AuthFilter
        - id: orders
          uri: lb://msvc-orders
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthFilter
        - id: products
          uri: lb://msvc-products
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthFilter
        - id: purchases
          uri: lb://msvc-purchases
          predicates:
            - Path=/api/v1/purchases/**
          filters:
            - AuthFilter
        - id: sales
          uri: lb://msvc-sales
          predicates:
            - Path=/api/v1/sales/**
          filters:
            - AuthFilter
        - id: suppliers
          uri: lb://msvc-suppliers
          predicates:
            - Path=/api/v1/suppliers/**
          filters:
            - AuthFilter
        - id: users
          uri: lb://msvc-users
          predicates:
            - Path=/api/v1/profile/**
          filters:
            - AuthFilter
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
