server:
  port: 8020

spring:
  application:
    name: msvc-billing
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/billing_system
    username: wuubzi
    password: Carlos31082005
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
