server:
  port: ${SERVER_PORT}
spring:
  application:
    name: msvc-billing

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

jpa:
  hibernate:
    ddl-auto: none
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  host: localhost
  port: 5672
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
